### PR TITLE
Add standard error attribute to glance_custom.fixest()

### PR DESCRIPTION
**Pull request by grantmcdermott**
Minor PR that adds some info about the standard error for fixest objects. Reprex:

``` r
devtools::load_all("~/Documents/Projects/modelsummary/")
#> Loading modelsummary
#> Loading required package: tables

library(fixest)
library(modelsummary)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/plm/EmplUK.csv'
dat <- read.csv(url)

mod <- list()
mod[[1]] <- feols(emp ~ wage, dat)
mod[[2]] <- feols(emp ~ wage | firm, dat)
mod[[3]] <- feols(emp ~ wage | firm + year, dat)
mod[[4]] <- summary(mod[[3]], se = "twoway")

msummary(mod, output = "markdown")
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Model 1</th>
<th style="text-align: left;">Model 2</th>
<th style="text-align: left;">Model 3</th>
<th style="text-align: left;">Model 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">15.228</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">(2.149)</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">wage</td>
<td style="text-align: left;">-0.307</td>
<td style="text-align: left;">-0.137</td>
<td style="text-align: left;">-0.062</td>
<td style="text-align: left;">-0.062</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">(0.087)</td>
<td style="text-align: left;">(0.061)</td>
<td style="text-align: left;">(0.050)</td>
<td style="text-align: left;">(0.054)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: left;">1031</td>
<td style="text-align: left;">1031</td>
<td style="text-align: left;">1031</td>
<td style="text-align: left;">1031</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: left;">0.012</td>
<td style="text-align: left;">0.981</td>
<td style="text-align: left;">0.983</td>
<td style="text-align: left;">0.983</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: left;">0.011</td>
<td style="text-align: left;">0.978</td>
<td style="text-align: left;">0.980</td>
<td style="text-align: left;">0.980</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2 Pseudo</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Within</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.016</td>
<td style="text-align: left;">0.003</td>
<td style="text-align: left;">0.003</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: left;">8625.3</td>
<td style="text-align: left;">4825.0</td>
<td style="text-align: left;">4751.9</td>
<td style="text-align: left;">4751.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: left;">8635.1</td>
<td style="text-align: left;">5521.2</td>
<td style="text-align: left;">5487.7</td>
<td style="text-align: left;">5487.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: left;">-4310.633</td>
<td style="text-align: left;">-2271.475</td>
<td style="text-align: left;">-2226.949</td>
<td style="text-align: left;">-2226.949</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FE × firm</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="even">
<td style="text-align: left;">FE × year</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Std. errors</td>
<td style="text-align: left;">Standard</td>
<td style="text-align: left;">Clustered (firm)</td>
<td style="text-align: left;">Clustered (firm)</td>
<td style="text-align: left;">Two-way (firm &amp; year)</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Nice, thanks.

Side effet of yesterday's change is that we get this:

Screen Shot 2020-08-05 at 21 14 11

Does the multiplication sign make sense for fixed effects, or should I change it?

**Comment by vincentarelbundock** [comment]
I'll merge this. The real solution is to replace : by x only for coefficients, not gof.

**Comment by grantmcdermott** [comment]
Cool, agree about the FEs.

As an aside: I originally thought about including another row corresponding to "Number of clusters" (turns out this is v. popular for economics journals, at least). But I think it gets complicated because of the way `fixest.summary()` adjusts SEs and DoF on the fly.

**Comment by vincentarelbundock** [comment]
Wouldn't it be reasonably easy to guess from the `fixef_id`? The number of elements in the list, and whether or not they have `^` in their names.

``` r
library(fixest)
library(dplyr)

n <- 1e5
dat <- data.frame(x = rnorm(n),
                  y = rnorm(n),
                  z = rnorm(n),
                  fe1 = sample(letters, n, replace = TRUE),
                  fe2 = sample(letters, n, replace = TRUE),
                  fe3 = sample(letters, n, replace = TRUE)) 

mod1 <- feols(y ~ x + z | fe1 + fe2 + fe3, dat)
mod2 <- feols(y ~ x + z | fe1 ^ fe2 + fe3, dat)

str(mod1$fixef_id)
#> List of 3
#>  $ fe1: int [1:100000] 15 15 17 3 24 26 11 24 14 5 ...
#>   ..- attr(*, "fixef_names")= chr [1:26] "c" "e" "n" "x" ...
#>  $ fe2: int [1:100000] 22 23 20 24 6 12 4 15 3 24 ...
#>   ..- attr(*, "fixef_names")= chr [1:26] "c" "e" "n" "x" ...
#>  $ fe3: int [1:100000] 5 22 17 20 19 24 4 13 12 19 ...
#>   ..- attr(*, "fixef_names")= chr [1:26] "c" "e" "n" "x" ...


str(mod2$fixef_id)
#> List of 2
#>  $ fe1^fe2: int [1:100000] 1 2 3 4 5 6 7 8 9 10 ...
#>   ..- attr(*, "fixef_names")= chr [1:676] "2215" "2315" "2017" "2403" ...
#>  $ fe3    : int [1:100000] 5 22 17 20 19 24 4 13 12 19 ...
#>   ..- attr(*, "fixef_names")= chr [1:26] "c" "e" "n" "x" ...
```

<sup>Created on 2020-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by grantmcdermott** [comment]
Unfortunately not. 

You can actually get the levels of the fixed effects directly from the fixest object with `dat$fixef_sizes`... and then conceivably match on (i.e. add up) whatever the cluster variables are. The problem with this approach, however, is that it doesn't account for the fact that fixest &mdash; similar to lfe, reghdfe (Stata), etc. &mdash; adjusts for nesting within clusters. So you'll get the wrong values. Laurent has a nice vignette discussing this all [here](https://cran.r-project.org/web/packages/fixest/vignettes/standard_errors.html).

Another approach might be to get the fixed effects "K" that goes into the the DoF calculation with `attr(vcov(mod1), "dof.K")` and work backwards from there... but I'm struggling to see how to do that consistently (again, b/c of how `summary.fixest()` calculates things on the fly).

At any rate, I don't mean to hijack this thread any longer. I should ask Laurent on the fixest repo ;)

**Comment by vincentarelbundock** [comment]
this is all interesting stuff. I'll read the vignette.

**Pull request merged**
