### PR TITLE
Automatically use variable labels

### PR DESCRIPTION
**Pull request by etiennebacher**
Hello Vincent, this PR is related to #460. It automatically detects labelled variables and replaces their name by their label. This works in `datasummary()`, `modelsummary()` and `modelplot()` (at least for basic examples), but not in `datasummary_skim()`. 

Two questions before going in the details:
* this adds a dependency on `sjlabelled`, mostly because it was more convenient for me to just have something that works. Do you want to remove it or are you ok with it?
* this PR automatically replaces variable names by their labels. Are you ok with that or do you want to add an argument? (if I remember correctly, you're not a big fan of super long args list but I prefer asking 😄)

## About `datasummary_skim()`

Using variable labels instead of variable names must be done in `datasummary`. If I'm not mistaken, after that, it is too late because `datasummary()` produces a kable, whose rownames can't be modified.
  
This creates a problem for `datasummary_skim()` because the formula is defined outside of `datasummary()` and the user has no control. Therefore, the data must be converted to numeric-only columns before calling `datasummary()`, which removes the label information. One way to bypass this is to get the ids of labelled columns, pass this as an argument to `datasummary()` and then deal with the labels in `datasummary()`. Clearly not optimal since it adds an argument only used for internal purposes to an exported function. 

For now, I don't see a solution for this but it's the first time I go in the internals of `modelsummary`. Maybe you'll have some idea.

#### `datasummary()`

``` r
suppressPackageStartupMessages({
  library(haven)
  library(sjlabelled)
  library(modelsummary)
})

mtcars$mpg <- haven::labelled(mtcars$mpg, label = "Miles per gallon")
mtcars$cyl <- haven::labelled(mtcars$cyl, label = "Number of cylinders")

datasummary(mpg + drat + cyl ~ mean + sd, data = mtcars, output = "dataframe")
#>                        mean   sd
#> 1    Miles per gallon 20.09 6.03
#> 2                drat  3.60 0.53
#> 3 Number of cylinders  6.19 1.79

datasummary(hp + mpg ~ Factor(cyl) * mean, data = mtcars, output = "dataframe")
#>                        4      6      8
#> 1               hp 82.64 122.29 209.21
#> 2 Miles per gallon 26.66  19.74  15.10

datasummary(hp + mpg ~ Mean * Arguments(fmt = "%.3f") + SD * Arguments(fmt = "%.1f"), data = mtcars, output = "dataframe")
#>                       Mean   SD
#> 1               hp 146.688 68.6
#> 2 Miles per gallon  20.091  6.0
```

<sup>Created on 2022-08-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

---

#### `modelsummary()` & `modelplot()`

``` r
library(modelsummary)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url)

dat$Literacy <- haven::labelled(dat$Literacy, label = "Literacy rate (%)")
dat$Clergy <- haven::labelled(dat$Clergy, label = "Number of monks")

models <- list(
  "OLS 1"     = lm(Donations ~ Literacy + Clergy, data = dat),
  "Poisson 1" = glm(Donations ~ Literacy + Commerce, family = poisson, data = dat),
  "OLS 2"     = lm(Crime_pers ~ Literacy + Clergy, data = dat),
  "Poisson 2" = glm(Crime_pers ~ Literacy + Commerce, family = poisson, data = dat),
  "OLS 3"     = lm(Crime_prop ~ Literacy + Clergy, data = dat)
)

modelsummary(models, output = "markdown")
```

|                   |   OLS 1    |  Poisson 1  |   OLS 2    |  Poisson 2  |   OLS 3    |
|:------------------|:----------:|:-----------:|:----------:|:-----------:|:----------:|
| (Intercept)       |  7948.667  |    8.241    | 16259.384  |    9.876    | 11243.544  |
|                   | (2078.276) |   (0.006)   | (2611.140) |   (0.003)   | (1011.240) |
| Literacy rate (%) |  -39.121   |    0.003    |   3.680    |    0.000    |  -68.507   |
|                   |  (37.052)  |   (0.000)   |  (46.552)  |   (0.000)   |  (18.029)  |
| Number of monks   |   15.257   |             |   77.148   |             |  -16.376   |
|                   |  (25.735)  |             |  (32.334)  |             |  (12.522)  |
| Commerce          |            |    0.011    |            |    0.001    |            |
|                   |            |   (0.000)   |            |   (0.000)   |            |
| Num.Obs.          |     86     |     86      |     86     |     86      |     86     |
| R2                |   0.020    |             |   0.065    |             |   0.152    |
| R2 Adj.           |   -0.003   |             |   0.043    |             |   0.132    |
| AIC               |   1740.8   |  274160.8   |   1780.0   |  257564.4   |   1616.9   |
| BIC               |   1750.6   |  274168.2   |   1789.9   |  257571.7   |   1626.7   |
| Log.Lik.          |  -866.392  | -137077.401 |  -886.021  | -128779.186 |  -804.441  |
| F                 |   0.866    |  18294.559  |   2.903    |   279.956   |   7.441    |
| RMSE              |  5740.99   |   5491.61   |  7212.97   |   7451.70   |  2793.43   |

``` r

modelplot(models[[1]])
```

<sup>Created on 2022-08-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
@etiennebacher, this is awesome. It’s definitely a feature I want to merge, so thanks for getting the ball rolling\!

I can’t dive deep into this right now, but here are few quick reactions:

1.  Is there an interaction with `coef_rename` and `coef_rename`?
      - Ideally, I think we would *not* use the labels if either of these arguments are non-`NULL`
      - Ideally, I think we would extract the labels early on, and then apply them through the existing `coef_rename` mechanism. There are lots of subtle issues about the order of operations which have been solved with `coef_rename` already, so we should re-use that if at all possible.
2.  Tests
      - `modelsummary` with interaction models
      - `modelsummary` with/without `coef_rename` and `coef_map`
      - `datasummary` with factor and numeric together
      - `datasummary` with multi-level row labels (nested left-hand-side formula)
      - Run tests with `output="dataframe"`
      - Anything else?
3.  The `gsub()` in `datasummary()` is too liberal. See below for an example that confuses to similarly named variables: `mpg` and `mpg2`
4. Renaming `datasummary` is not as simple as changing the row names, because...
    - Nested operations on the left-hand side of the formula
    - Factor + Numeric variables produced "misaligned" variable names
    - Variables can be in columns
5.  Yeah, I think it would be really nice if we could avoid a new dependency; There are so many already :(
      - What’s the “standard” structure labels?
      - Is it a global data.frame level attribute, or column-specific info?
      - Do different packages save labels in different formats?

Thanks\!

``` r
suppressPackageStartupMessages({
  library(haven)
  library(sjlabelled)
  library(modelsummary)
})

dat <- mtcars
dat$mpg <- haven::labelled(dat$mpg, label = "Miles per gallon")
dat$mpg2 <- haven::labelled(dat$mpg, label = "Miles per gallon")
dat$cyl <- as.factor(dat$cyl)
dat$cyl <- haven::labelled(dat$cyl, label = "Number of cylinders")

datasummary(
    mpg + Factor(cyl) ~ N + mean + sd,
    data = dat,
    output = "markdown")
```

|                     |     |  N |  mean |   sd |
| :------------------ | :-- | -: | ----: | ---: |
|                     | mpg | 32 | 20.09 | 6.03 |
| Number of cylinders | 1   | 11 |       |      |
|                     | 2   |  7 |       |      |
|                     | 3   | 14 |       |      |

``` r

mod <- list(
    lm(hp ~ mpg + drat + cyl, data = dat),
    lm(hp ~ mpg2 * drat + cyl, data = dat))

modelsummary(mod, "markdown")
```

|                         |  Model 1  |  Model 2  |
| :---------------------- | :-------: | :-------: |
| (Intercept)             | \-45.114  | \-232.024 |
|                         | (90.822)  | (197.093) |
| Miles per gallon        |  \-3.899  |   5.218   |
|                         |  (2.072)  |  (8.784)  |
| drat                    |  40.961   |  88.149   |
|                         | (17.115)  | (47.374)  |
| Number of cylinders     |  58.658   |  61.554   |
|                         | (14.338)  | (14.557)  |
| Miles per gallon × drat |           |  \-2.313  |
|                         |           |  (2.166)  |
| Num.Obs.                |    32     |    32     |
| R2                      |   0.759   |   0.768   |
| R2 Adj.                 |   0.733   |   0.734   |
| AIC                     |   324.9   |   325.6   |
| BIC                     |   332.2   |   334.4   |
| Log.Lik.                | \-157.443 | \-156.781 |
| F                       |  29.335   |  22.397   |
| RMSE                    |   33.15   |   32.48   |

**Comment by etiennebacher** [comment]
1. Right, I didn't know these args but it makes sense. I added an argument `coef_use_labels` (temporary name, let me know what you think) and a few tests to check that `coef_rename` and `coef_map` have the priority over this new arg. What I did so far is far from robust and I'm not sure yet about the right way to implement this. This turns out more complicated than I thought because there are a lot of corner cases. I'll try to write a maximum of tests to ensure all the behaviors are correct.
2. /
3. I added `^` and `$` in `gsub()` but I guess it won't work for all cases (e.g interactions). Like 1., I need to think more about how to handle this.
4. /
5. I think there are two main classes that represent labelled variables: `haven_labelled` and `labelled`. If the variable is labelled, it should have an attribute `label` (so it is column-specific, not dataframe-specific). I copied `sjlabelled`'s `get_label()` and `is_labelled()` without all the checks and stuff since this function is not exported and we can simply apply it on each variable. So there's no more dependency on `sjlabelled`.

**Comment by vincentarelbundock** [comment]
Cool cool. I don't think we need an extra argument. Here's one "logic" with pseudo-code:

```r
if (!is.null(coef_rename)) {
  # do no thing, keep going as usual
} else if (is.null(coef_rename)) {
  lab <- lapply(models, get_labels)
  # fail gracefully if `insight::get_data` does not work (sometimes happen, in my experience)
  # make sure there are no models estimated on different data frames with conflicting labels
  # dynamically build a coef_rename_label() function
  coef_rename <- coef_rename_label
}
# since `coef_rename` is now a function, everything should work automatically
```

Note that the `coef_rename`  argument accepts arbitrary functions, as long as they take a character vector and return a character vector of the same length. So we can "dynamically" create a renaming function called `coef_rename_label()`, which loops over the labels, and creates regexes to replace instances bounded by `^$`, but also `:$`, `^$`, and `::`, and `gsub()` the coefficient name vector.

**Comment by vincentarelbundock** [comment]
For `datasummary()`, internally we call the row names labels a "stub". That might help you find the relevant number of columns, etc.

**Comment by etiennebacher** [comment]
For info, when a function is used in the formula (`scale`, `factor`, etc.), `insight::get_data()` removes the `haven_labelled` class, which makes it impossible to replace these variables with their labels:
``` r
dat <- mtcars[, c("mpg", "cyl")]
dat$cyl <- haven::labelled(dat$cyl, label = "Number of cylinders")
lapply(dat, class)
#> $mpg
#> [1] "numeric"
#> 
#> $cyl
#> [1] "haven_labelled" "vctrs_vctr"     "double"

# Works
x <- lm(mpg ~ cyl, data = dat)
lapply(insight::get_data(x), class)
#> $mpg
#> [1] "numeric"
#> 
#> $cyl
#> [1] "haven_labelled" "vctrs_vctr"     "double"

# Doesn't work
x <- lm(mpg ~ factor(cyl), data = dat)
lapply(insight::get_data(x), class)
#> $mpg
#> [1] "numeric"
#> 
#> $cyl
#> [1] "numeric"

x <- lm(mpg ~ scale(cyl), data = dat)
lapply(insight::get_data(x), class)
#> $mpg
#> [1] "numeric"
#> 
#> $cyl
#> [1] "numeric"

x <- lm(mpg ~ I(cyl^2), data = dat)
lapply(insight::get_data(x), class)
#> $mpg
#> [1] "numeric"
#> 
#> $cyl
#> [1] "AsIs"
```

<sup>Created on 2022-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by etiennebacher** [comment]
I don't know what to do when two different variables in two different models and potentially coming from two different datasets have the same label. In your example above, they share the same row in the table. Should they be separated? If so, how can we distinguish the two rows?

IMO, we should issue a warning when two variables share the same label because I doubt that would be intentional.

**Comment by vincentarelbundock** [comment]
I feel that people often ignore warnings, and that this has the potential to introduce critical errors in reported results. So we should not rename variables at all when there are conflicts.

How about this? If two variables have the same label and same colname, we proceed. If two variables have the same label but different colnames, or same colnames but different labels, we keep `coef_rename=NULL` and we issue an informative warning message. Users can then rename the column to avoid the problem.

**Comment by etiennebacher** [comment]
> How about this? If two variables have the same label and same colname, we proceed. If two variables have the same label but different colnames, or same colnames but different labels, we keep coef_rename=NULL and we issue an informative warning message. Users can then rename the column to avoid the problem.

Seems good. I think most cases are covered below. The code is not clean and I think it could be faster but I won't be available for the next couple of weeks so I put my progress here in case you or someone else want to build on that.

``` r
library(modelsummary)

dat1 <- mtcars
dat1$mpg <- haven::labelled(dat1$mpg, label = "Miles per gallon")
dat1$cyl <- haven::labelled(dat1$cyl, label = "Miles per gallon")
dat1$wt <- haven::labelled(dat1$wt, label = "Weight (1000 lbs)")

dat2 <- mtcars
dat2$mpg2 <- haven::labelled(dat2$mpg, label = "Miles per gallon")
dat2$wt <- haven::labelled(dat2$wt, label = "Weight (1000 lbs)")

# mpg and cyl have the same label
should_warn_within <- list(
  lm(hp ~ mpg + cyl, dat = dat1),
  lm(hp ~ mpg + wt, dat = dat2)
)

# mpg and mpg2 have the same label
should_warn_across <- list(
  lm(hp ~ mpg + drat, dat = dat1),
  lm(hp ~ mpg2 + wt, dat = dat2),
  lm(Sepal.Length ~ Sepal.Width, data = iris)
)

# the two above combined
should_warn_within_and_across <- list(
  lm(hp ~ mpg + cyl, dat = dat1),
  lm(hp ~ mpg2 + wt, dat = dat2)
)

# fine
should_not_warn <- list(
  lm(hp ~ mpg + wt, dat = dat1),
  lm(hp ~ mpg + wt, dat = dat2)
)

x1 <- modelsummary(should_warn_within, output = "markdown")
#> Warning: Model number 1 has duplicated labels. Labels were not used in
#> `modelsummary()`.
x2 <- modelsummary(should_warn_across, output = "markdown")
#> Warning: Some variables in models [1, 2] have different names but identical
#> labels. Labels were not used in `modelsummary()`.
x3 <- modelsummary(should_warn_within_and_across, output = "markdown")
#> Warning: Model number 1 has duplicated labels. Labels were not used in
#> `modelsummary()`.
#> Warning: Some variables in models [1, 2] have different names but identical
#> labels. Labels were not used in `modelsummary()`.
x4 <- modelsummary(should_not_warn, output = "markdown")
```

<sup>Created on 2022-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Thanks for all your work on this @etiennebacher 

I merge a simplified version of your PR: https://github.com/vincentarelbundock/modelsummary/pull/539

Try it out and let me know what you think. Basically all the work in done in `utils_labels.R`, and then in 2 lines of code in `modelsummary.R`

It only works for `modelsummary`, since `datasummary` will be much more complicated. I think we should really think of an implementation plan before starting to code on `datasummary`.

**Comment by vincentarelbundock** [comment]
I now got things to work with `datasummary_skim()`, `datasummary()`, and `datasummary_crosstab()`, and `datasummary_correlation()`. The only one missing is `datasummary_balance()`, which turned out to be a fair bit more complicated, because the `All()` pseudo-function does not work with labelled data.

I will close this PR now since it has basically been integrated in different ways.

Thanks again for your work on this, and don't hesitate to open discussions for new submissions. I love it!

**Pull request closed without merging**
