### PR TITLE
Add dvnames function for dependent variable-titled columns

### PR DESCRIPTION
**Pull request by NickCH-K**
Adds a new function, dvnames, that can be passed a model or list of models and returns a named list of those models, where the dependent variables are the names, which can then be passed to modelsummary.

### CODE REVIEW

**Comment by NickCH-K** [comment]
Hmm, a bit confused by the code checks, as the failures seem to be coming from files other than `test-dvnames.R`

**Comment by vincentarelbundock** [comment]
Looks great to me, thanks so much!

Don't worry about the code checks. It has to do with measuring test coverage, not actual test breakage, and it was there before your PR.

Feel free to add a bullet to the NEWS and your contacts to the contributor section of the DESCRIPTION if you want. Then I can merge.

**Comment by NickCH-K** [comment]
Done!

**Comment by vincentarelbundock** [comment]
Fantastic! Thanks again. This is a really neat feature.

**Pull request merged**
