### PR TITLE
Add info to mice lm models

### PR DESCRIPTION
**Pull request by LukasWallrich**
This pull request primarily adds some information to the tidy.mira and glance.mira output when the mira object consists of lm models. This facilitates showing them alongside normal lm models with confidence intervals, p-values and R2.

It also slightly modifies the documentation that referred to tidying outputs from mice::pool() (i.e. mipo rather than mira objects). Finally, it changes a line that led to the term names getting dropped.

Hope this is helpful - let me know if you'd like any further edits. Thanks for the wonderful package!

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Looks fantastic, thanks! Do you think you could:

1. Add a bullet point to NEWS.md (0.2.0 is not released yet, so it could go under there)
2. Rebuild the roxygen2 docs with devtools::document()
3. Squash commits and force push so that I can merge a single commit

Don't worry if that's not possible, I can take care of that if you don't

**Comment by LukasWallrich** [comment]
I've done 1 and 2, and probably 3, though I am relatively new to git and not entirely sure if it worked as intended.

**Comment by vincentarelbundock** [comment]
Looks great!

I merged. It might be worth installing from github on your machine and trying with some real models to see if it worked, but the code looks good to me.

`gt` just got submitted to CRAN, and the windows binaries haven't reached it yet. When they are there, I'll submit this new version to CRAN. My guess is it will take a couple days.

Thanks again!

**Comment by LukasWallrich** [comment]
I now tested it with some of my models and it works as expected - that makes `modelsummary()` a lot more useful for the dissertation I am working on :) Thanks for integrating this so quickly.

**Comment by vincentarelbundock** [comment]
Cool. FYI, I submitted a pull request to `broom`. It would make much more sense to have this integrated upstream. If they do integrate it, the tidiers in `modelsummary` will disappear.

https://github.com/tidymodels/broom/pull/827

**Pull request merged**
