### PR TITLE
Add arguments to rename polynomials with `coef_rename()`

### PR DESCRIPTION
**Pull request by mccarthy-m-g**
This PR updates `coef_rename()` to handle polynomial coefficients created by the `poly()` function, similar to how the function currently handles factors. Here's some reprex code to check the new functionality out:

```r
x <- list(
    lm(mpg ~ poly(cyl, 2) + drat + disp, data = mtcars),
    lm(hp ~ poly(cyl, 2, raw = TRUE) + drat + disp, data = mtcars)
)

# Results in polynomial names of the form '^1', '^2', etc.
modelsummary(dvnames(x), coef_rename = coef_rename)

# Results in polynomial names of the form 'Cyl^1', 'Cyl^2', etc.
modelsummary(dvnames(x), coef_rename = \(.x) coef_rename(.x, poly_name = FALSE))
```

Note that I didn't update `NEWS` or add any tests yet (I'm unfamiliar with `tinytest`, so I'm unsure how to go about it).

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Oh thanks, this is a really great idea! Awesome.

Two questions:

1. Could we combine the two arguments? Maybe `poly` doesn't have to be TRUE/FALSE and can immediately say what "style" we want.
2. Will the default style work in all output formats? For example, I believe `Cyl^2` would break LaTeX compilation, and is not valid markdown either.

**Comment by mccarthy-m-g** [comment]
Welcome! Regarding your questions:

> Will the default style work in all output formats? For example, I believe Cyl^2 would break LaTeX compilation, and is not valid markdown either.

This approach just lets us clean up `poly()` coefficients to get the same result we would get if we cleaned up polynomials that were constructed "by hand" with `I()`:

```r
x <- list(
    lm(mpg ~ I(cyl^1) + I(cyl^2) + drat + disp, data = mtcars),
    lm(mpg ~ poly(cyl, 2, raw = TRUE) + drat + disp, data = mtcars)
)
modelsummary(x, coef_rename = \(.x) coef_rename(.x, poly_name = FALSE))
```

So the intention isn't to print the exponents in superscript---just as is. I don't believe this should break any output formats unless you attempt to apply some post-processing to the string that results in something breaking. But if that's the case you'd need special handling for `I()` statements too.

> Could we combine the two arguments? Maybe poly doesn't have to be TRUE/FALSE and can immediately say what "style" we want.

I think it makes sense to stick with a boolean argument for `poly`, since every other argument for `coef_rename()` is also a boolean.

What we could do though is reduce it to a single boolean argument for the `Cyl^2` style. I only included the `^2` style based on the options you currently give for factors---but personally I don't think this style is particularly useful, so I'd just drop it unless you can imagine a use case.

**Comment by vincentarelbundock** [comment]
Got it. 

Yes, let's simplify to a single bool with the style you prefer.

The ^ character should really be tested in a latex document though (or Quarto/Rmd PDF), because I think it's a special character.

If that's the case and it breaks compilation, we either need some more complicated logic to escape conditionally on output format (would be a pain to code), or we need to come up with a different default style.

**Comment by vincentarelbundock** [comment]
Oh I see your point about `I(x^2)`.

I think that works because modelsummary escapes this character by default.

So we're fine on that front.

**Comment by mccarthy-m-g** [comment]
Awesome. I simplified the code to do the `Cyl^2` style when `poly = TRUE`, so this gives nice output by default now:

```r
x <- list(
    lm(mpg ~ I(cyl^1) + I(cyl^2) + drat + disp, data = mtcars),
    lm(mpg ~ poly(cyl, 2, raw = TRUE) + drat + disp, data = mtcars)
)
modelsummary(x, coef_rename = coef_rename)
```

Since `^` is escaped by default, we don't need to worry about testing in a latex document now, correct?

**Comment by vincentarelbundock** [comment]
Thanks a ton for this! Looks great.

I merged.

The latest release was only a few days ago, so it'll take a little bit before this gets to CRAN, but it should be available on Github and R-Universe in the next few minutes.

**Comment by mccarthy-m-g** [comment]
Happy to contribute! I've been using modelsummary frequently for the example articles of a [data package I'm working on](https://mccarthy-m-g.github.io/alda/index.html) and it's been super useful.

Thanks for merging!

**Pull request merged**
