### PR TITLE
add actions to compute code coverage and detect lints

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Some actions are failing because binaries for `gert` package are not built yet, and there is an error while compiling the package from source.

**Comment by vincentarelbundock** [comment]
Thanks, looks great! We can wait for `gert` binaries to come live and try again. Two questions:

1. Does the coverage code respect `.covrignore`?
2. What is the intended goal of the lintr?

I admit that I'm a bit skeptical of linters in general. For instance, when I ran `lintr::lint_package()` I got thousands of "hits" in the test folder. Most of them related to (a) `=` instead of `<-`, (b) spaces around infix operators,  (c) double-quotes instead of single-quotes, (d) commented out quotes, and (e) long lines of `dput` code.

Obviously, I agree that maintaining a consistent code style is important, and I have done so in the main package, but not the tests which I have written quickly.

My personal experience with auto-formatting has been terrible, and I am very unlikely to merge a commit that modifies 500 lines of code, especially if it risks introducing weird line breaks. I'm also unlikely to comb through hundreds of lines of test just to add white space.

So I guess I'm wondering what's the payoff? Is this just going to raise new errors that nag me every time?

To be clear, I'm not saying I don't like this. I'm genuinely curious about the auto-linting benefits.

**Comment by IndrajeetPatil** [comment]
> Does the coverage code respect .covrignore?

To the best of my knowledge, it does.

> My personal experience with auto-formatting has been terrible, and I am very unlikely to merge a commit that modifies 500 lines of code, especially if it risks introducing weird line breaks. I'm also unlikely to comb through hundreds of lines of test just to add white space.

`lintr` will not change anything! It only flags the lints. For example, here are lints from a recent [build](https://github.com/IndrajeetPatil/statsExpressions/runs/1905159495) of my package:

Screenshot 2021-02-16 at 13 42 37

This action doesn't have permission to modify anything in the code itself. It just provides helpful feedback. You can act on it, or completely ignore it.

> I admit that I'm a bit skeptical of linters in general. For instance, when I ran lintr::lint_package() I got thousands of "hits" in the test folder. Most of them related to (a) = instead of <-, (b) spaces around infix operators, (c) double-quotes instead of single-quotes, (d) commented out quotes, and (e) long lines of dput code.

A lot of these would disappear if you just run once `styler::style_dir()`. 

Also, if you want to avoid certain lints from being flagged, you can change the `.lintr` config file I have introduced in my PR.
For example, one of the lints is about keeping code lines to 80-character width, but I think that's too strict. So I have changed it to 120. So the lintr action will flag the lines which are over 120-character width. Etc. You can change its behavior anyway you want.

**Comment by IndrajeetPatil** [comment]
I think you will have a better idea about the behavior of these actions once they work in this `PR` itself.

We will just have to wait and try again when `gert` is not complaining any more.

**Comment by vincentarelbundock** [comment]
Alright, all of this is reassuring. Let's wait and see. 

Thanks again!

**Comment by IndrajeetPatil** [comment]
Should work now.

**Comment by IndrajeetPatil** [comment]
Oh, I think you need to link to `codecov` through your GitHub profile and give it access to your repos so that you can see the code coverage there.

**Comment by vincentarelbundock** [comment]
Hmm, that's weird. Do you know how I should do that? My accounts are already linked, since I granted codecov access to the github repo (`modelsummary` is in my list of repositories on the codecov site).

And the `codecov` error is not super informative, unfortunately:

```
Error: Error: Failure in `/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmpiu5iTd/R_LIBS7022dc6932d/modelsummary/modelsummary-tests/testthat.Rout.fail`
Execution halted
Error: Process completed with exit code 1.
```

**Comment by IndrajeetPatil** [comment]
Hmm, that's strange indeed. I guess you can just merge this and see if it works when the action is run from `master`. 

If not, just delete the `test-coverage.yml` file since it is useless if codecov can't access your repo for some reason  🤷‍♂️

**Comment by vincentarelbundock** [comment]
Hmm, looks like it doesn't work. Not a big deal. I don't have time to mess around with this now, but I opened an issue and maybe someone will come around with a solution.

**Comment by vincentarelbundock** [comment]
thanks again!

**Pull request merged**
