### PR TITLE
Set hrule to NULL if NA to allow creation of models without GOFs

### LINKED ISSUE #61: Add gof_omit = "all" option
For me, it would be very helpful to have a simple way to exclude gof in the msummary call. Would you be open to considering a PR that implements gof_omit = "all"? It would add half a line to the msummary documentation, though :)

(Background to my gof struggles): I am often showing the same model with differently scaled coefficients, and don't want to show gof twice, as in the below)

Example

### PR DESCRIPTION
**Pull request by LukasWallrich**
This fixes #61 for me.

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
@LukasWallrich Thanks so much for this extremely detailed report and for the PR. Without all this, I would have wasted a bunch of time tracking this down, so this is *super* helpful!

My slight preference is to fix this by adding another check in the `if` statement 3 lines above the one you modified. I pushed a commit with this slight tweak to your fix:

https://github.com/vincentarelbundock/modelsummary/commit/f63598eb233f6d2e073c979732c6123a221fab5b

That commit also includes a new mini-test to guard against future regression:

https://github.com/vincentarelbundock/modelsummary/blob/master/tests/testthat/test-gt.R

Let me know if the Github version works for you. I plan to release a new version to CRAN in the next few days.



Somewhat unrelated, but I probably should warn you that there is a high likelihood that the default HTML output will be produced by `kableExtra` in the next version (`gt` will still be supported, of course). See the rationale here:

https://github.com/vincentarelbundock/modelsummary/issues/116

**Comment by LukasWallrich** [comment]
Thanks - this works! I also appreciate the warning - I have lots of msummary() %>% gt::x() pipes in my rNuggets utility package, so I will make sure to update that in time.

**Comment by LukasWallrich** [comment]
Just another quick question: do you remember what happened to the tidy.mira and glance.mira methods? If I remember correctly, you wanted them to move to broom, where they belong - but I don't think they made it there?

**Comment by vincentarelbundock** [comment]
@LukasWallrich I submitted a patch to the `mice` package to integrate them directly to that package. The `mice` author made a compelling argument that we should supply `tidy` methods for `mipo` objects, and not `mira`, so the recommended workflow is described here:

https://vincentarelbundock.github.io/modelsummary/articles/multiple_imputation.html

There's a note at the top of that page mentioning that this works with the devel version of `mice`, but I believe the methods have since made their way to CRAN.

Let me know if that works for you.

**Pull request closed without merging**
