### PR TITLE
Change to format_estimates to deal with models with more than 500 coefs

### PR DESCRIPTION
**Pull request by moritzpschwarz**
See more detail in #274

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Thanks a lot for looking into this @moritzpschwarz !

I'm happy to merge immediately, but you can also add yourself as a contributor in the DESCRIPTION if you like. Let me know if you want to do that or if I should click "Merge" right away.

**Comment by moritzpschwarz** [comment]
Awesome, that's great!!

And it's you we need to thank for the great package ;) Many, many thanks for the suggestion - really not something that is expected or needed, but definitely appreciate the gesture, so added it quickly now!

**Comment by moritzpschwarz** [comment]
Apologies, just added one too many `)` - should be fixed now

**Comment by vincentarelbundock** [comment]
Rainbow parentheses FTW!

**Pull request merged**
