### PR TITLE
Std. error display and vcov args

### PR DESCRIPTION
**Pull request by grantmcdermott**
See: #360 (and especially https://github.com/vincentarelbundock/modelsummary/issues/360#issuecomment-900809668).

Checklist:

- [ ] Consistent SE names and/or dictionary (possibly beyond scope)
- [x] Consistent printing of clustered SEs (`by: var1 & var2`)
- [ ] Dynamic `vcov = "robust"` based on model object and call
- [ ] Infer default behaviour if `vcov = NULL`
- [ ] vcov whitelist (posssibly beyond scope)

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Don’t worry about the old failing tests for now. A lot of them are hard coded and will need to be updated. Just write new ones as needed and we can reconcile the rest later.

Thanks!

**Comment by vincentarelbundock** [comment]
FYI, I merged this into main today and made a few minor tweaks.

All of the `fixest`-related code now lives in a separate file: https://github.com/vincentarelbundock/modelsummary/blob/main/R/methods_fixest.R

The idea is that `get_vcov.fixest` takes care of extracting standard errors based on the user-suppled value of `vcov`, and `glance_custom_internal.fixest` sets the label that appears in the GOF section.

I think this makes things a bit cleaner and easier to extent.

Thanks for the PR! I like the new clustered labels!

**Comment by grantmcdermott** [comment]
Ah, sorry mate. I _completely_ dropped the ball with this. 

(Tbh the whole "robust" discussion stole my mojo... I still have code lying around that implements the original proposed fix. I can push to this branch if you want to have a look. Or is the idea that it will be an alias for HC1?)

**Comment by vincentarelbundock** [comment]
Oh now worries. I'm super glad to have the code you committed already!

And yeah, anything else you have and could easily push would be useful. But remind me: the code you have is for figuring out what the "native" `fixest` or `estimatr`-specific meaning of "robust" is? If so, I think this would be really great and would fit nicely in the `get_vcov.CLASSNAME` methods.

**Comment by grantmcdermott** [comment]
I think that's right, though I'll need to take another look. I'll also check out the `get_vcov.CLASSNAME` stuff.

**Pull request closed without merging**
