### PR TITLE
Consistent gof printing of cluster variables

### PR DESCRIPTION
**Pull request by grantmcdermott**
Current behaviour:

``` r
library(fixest)
library(lfe)
#> Loading required package: Matrix
library(estimatr)

mod_feols =   feols(hp ~ mpg + drat, mtcars, vcov = ~vs)
mod_felm =     felm(hp ~ mpg + drat |0 | 0 | vs, mtcars)
mod_rob = lm_robust(hp ~ mpg + drat, mtcars, se_type = 'stata', clusters = vs)

mods = list('feols' = mod_feols, 'felm' = mod_felm, 'lm_robust' = mod_rob)

library(modelsummary)

msummary(mods, gof_omit = 'Obs|R2|IC|Lik|se_type', output = 'markdown')
```

|             |     feols      |   felm   | lm_robust |
|:------------|:--------------:|:--------:|:---------:|
| (Intercept) |    278.515     | 278.515  |  278.515  |
|             |    (20.573)    | (20.573) | (20.573)  |
| mpg         |     -9.985     |  -9.985  |  -9.985   |
|             |    (4.110)     | (4.110)  |  (4.110)  |
| drat        |     19.126     |  19.126  |  19.126   |
|             |    (32.644)    | (32.644) | (32.644)  |
| Std. Errors | Clustered (vs) |          |           |

<sup>Created on 2021-08-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

With proposed change:

``` r
library(fixest)
library(lfe)
#> Loading required package: Matrix
library(estimatr)

mod_feols =   feols(hp ~ mpg + drat, mtcars, vcov = ~vs)
mod_felm =     felm(hp ~ mpg + drat |0 | 0 | vs, mtcars)
mod_rob = lm_robust(hp ~ mpg + drat, mtcars, se_type = 'stata', clusters = vs)

mods = list('feols' = mod_feols, 'felm' = mod_felm, 'lm_robust' = mod_rob)

library(modelsummary)

msummary(mods, gof_omit = 'Obs|R2|IC|Lik|se_type', output = 'markdown')
```

|             |     feols      |   felm   | lm_robust |
|:------------|:--------------:|:--------:|:---------:|
| (Intercept) |    278.515     | 278.515  |  278.515  |
|             |    (20.573)    | (20.573) | (20.573)  |
| mpg         |     -9.985     |  -9.985  |  -9.985   |
|             |    (4.110)     | (4.110)  |  (4.110)  |
| drat        |     19.126     |  19.126  |  19.126   |
|             |    (32.644)    | (32.644) | (32.644)  |
| Std. Errors | Clustered (vs) | Clustered (vs) | Clustered (vs) |

<sup>Created on 2021-08-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Very nice! I tried adding a test but am getting the wrong result for the `feols` model:

```r


+ library(modelsummary)
+ library(fixest)
+ library(lfe)
+ library(estimatr)
+ 
> 
+ mod = list(
+     "feols" = feols(hp ~ mpg + drat, mtcars, vcov = ~vs),
+     "felm" = felm(hp ~ mpg + drat |0 | 0 | vs, mtcars),
+     "estimatr" = lm_robust(hp ~ mpg + drat, mtcars, se_type = 'stata', clusters = vs))
+ 
+ Warning message:
feols(fml = hp ...: vcov is not a valid argument for function feols. 
> 
+ msummary(mod, gof_omit = 'Obs|R2|IC|Lik|se_type', output = 'markdown')
+ 
> 

|            |  feols   |      felm      |    estimatr    |
|:-----------|:--------:|:--------------:|:--------------:|
|(Intercept) | 278.515  |    278.515     |    278.515     |
|            | (55.415) |    (20.573)    |    (20.573)    |
|mpg         |  -9.985  |     -9.985     |     -9.985     |
|            | (1.792)  |    (4.110)     |    (4.110)     |
|drat        |  19.126  |     19.126     |     19.126     |
|            | (20.198) |    (32.644)    |    (32.644)    |
|Std.Errors  | Standard | Clustered (vs) | Clustered (vs) |
> 
```

**Comment by vincentarelbundock** [comment]
Here's a simple test we may want to add to the `test-supported.R` file:


```r
test_that("consistent gof std error display fixest/lfe/estimatr", {
    skip_if_not_installed(c("fixest", "lfe", "estimatr"))
    library(fixest)
    library(lfe)
    library(estimatr)
    mod <- list(
        "feols" = feols(hp ~ mpg + drat, mtcars, vcov = ~vs),
        "felm" = felm(hp ~ mpg + drat |0 | 0 | vs, mtcars),
        "estimatr" = lm_robust(hp ~ mpg + drat, mtcars, se_type = 'stata', clusters = vs))
    tab <- msummary(mod, gof_omit = 'Obs|R2|IC|Lik|se_type', output = 'data.frame')
    expect_equal(tab$feols[nrow(tab)], "Clustered (vs)")
    expect_equal(tab$felm[nrow(tab)], "Clustered (vs)")
    expect_equal(tab$estimatr[nrow(tab)], "Clustered (vs)")
})
```

**Comment by grantmcdermott** [comment]
Thanks! The problem here is that I'm using the soon-to-be-released 0.10.0 version of fixest, which introduces the ['vcov'](https://lrberge.github.io/fixest/articles/fixest_walkthrough.html#the-vcov-argument-1) argument. This also impacts my other recent PR, only moreso, so I'll add a more detailed comment there.

I'll add the test, though and include a slight variation for versions lower than 0.10.0.

**Comment by grantmcdermott** [comment]
I've got to run for a sec, but I think there's bigger conversation to be had about consistent gof printing for adjusted SEs in general. I'm happy to continue that discussion here or in a separate issue/PR, so will just leave a quick example.

``` r
library(fixest)
library(estimatr)
library(modelsummary)

mod_feols_hc =   feols(hp ~ mpg, mtcars, vcov = 'hetero')
mod_rob_hc = lm_robust(hp ~ mpg, mtcars, se_type = 'stata')

mods_hc = list('feols HC' = mod_feols_hc, 'lm_robust HC' = mod_rob_hc)

msummary(mods_hc, 
         output = 'markdown', 
         gof_omit = 'Obs|R2|IC|Lik')
```

|             |         feols HC          | lm_robust HC |
|:------------|:-------------------------:|:------------:|
| (Intercept) |          324.082          |   324.082    |
|             |         (28.821)          |   (28.821)   |
| mpg         |          -8.830           |    -8.830    |
|             |          (1.256)          |   (1.256)    |
| Std. Errors | Heteroskedasticity-robust |              |
| se_type     |                           |     HC1      |

<sup>Created on 2021-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by vincentarelbundock** [comment]
Thanks, this looks fantastic!

**Pull request merged**
